site_name: Conrad Ho Profile
nav:
  - Home: index.md
  - Physics:
      - About Me: Physics/physics.md
      - Year 1:
          - Summer Project:
              - Physics/Year 1/Summer Project 2025/Summer Project 2025.md 
                
  - Music: Music/music.md
  

markdown_extensions:
  - mdx_math
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_HTML
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js